### ISSUE TITLE
Android Stuido -> ERROR: path\twist.moe\secrets.properties (The system cannot find the file specified)

### ISSUE THREAD

**Issue by vahnbastian** [ATechnoHazard/twist.moe#14]
It looks like the file specific has been missing from the root folder mate. Or maybe I did some mistake? Please help

**Comment by ATechnoHazard** [comment]
This is a file that contains some secret keys for decrypting anime twist
source URLs.

Message me on telegram at t.me/SphericalKat and we'll see if I can release
them to you :)

**Comment by nusayba14** [comment]
sorry @ATechnoHazard can I please ask why the app suddenly stopped working
