### ISSUE TITLE
An option to sort episodes by latest

### ISSUE THREAD

**Issue by akashrajum7** [ATechnoHazard/twist.moe#2]
It would be nice to have an option to sort episodes from latest to old as it will be easy to play latest episode on ongoing series. Unfortunately I'm not familiar with Kotlin, so all i can do is give an idea.

Thank you.

**Comment by ATechnoHazard** [comment]
Hi, thanks for your interest :)

**Comment by akashrajum7** [comment]
Thank you! :)

**Comment by ATechnoHazard** [comment]
Added a button to scroll to the bottom of the episode list in cc83738
